### ISSUE TITLE
Update doc in developer guide on when to use injectIntl vs contextTypes vs FormattedMessage component and standardize testing these different approaches

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#119]
# Issue Description
Need to make it clear in our developer contribution guide when to use injectIntl vs contextTypes vs FormattedMessage component and standardize testing these different approaches.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Developer guide explains when to use injectIntl vs contextTypes vs FormattedMessage component and standardize testing these different approaches.

**Comment by noahbenham** [comment]
We've preferred the **`contextTypes`** strategy so far because it eliminates the extra wrapper around our components. This is especially relevant with Reduxified components that already have a wrapper.

So with the current legacy context,
```jsx
export default class MyComponent extends React.Component {
  static contextTypes = { intl: () => {} };
  
  render() {
    <div>{this.context.intl.formatMessage({ id: '...' })</div>
  }
}
```

I believe the migration path forward to the new context API using this strategy could look something like
```jsx
import ContextType from 'terra-base/.../ContextType';

export default class MyStatusCard extends React.Component {
  static contextType = ContextType;
  
  render() {
    <div>{this.context.intl.formatMessage({ id: '...' })</div>
  }
}
```

The **`FormattedMessage`** strategy wasn't universally effective for us because it returns a react component. There are many places where a plain text string is preferred. For example, React would throw a prop type warning doing this:
```jsx
<Alert
  type={Alert.Opts.Types.CUSTOM}
  title={<FormattedMessage id="Connect.Alerts.someIntlId" } // Not a String type
  customIcon={<IconDoNotDisturb />}
  />
```

**Comment by noahbenham** [comment]
If one approach is generally preferred over others going forward, it could be particularly important to reflect that in the component starter as many teams use that as a source of truth for the community standard.

**Comment by RHolland13** [comment]
You can use the render prop version of `FormattedMessage` for the case where you need a string.  eg
```jsx
<FormattedMessage id="Connect.Alerts.someIntlId" >
  {(alertText) =>
    <Alert
      type={Alert.Opts.Types.INFO}
      title={alertText} // Not a String type
    />
  }
</FormattedMessage>
```
Not the most concise option, but still saves you from using `injectIntl`.

**Comment by bjankord** [comment]
This is really good feedback. I think FormattedMessage can be good solution, but I'm unsure about always recommending it. There are some props we need to keep as strings due to the fact that the underlying HTML attribute we pass the prop to only accepts string. As a contrived example, let's say we have a component like the following where label and placeholder map directly the HTML attributes on an input.

```jsx
<Input label={localeLabel} placeholder={localePlaceholder) />
```

Using the render props version of `<FormattedMessage />`, we could get around this with nested `<FormattedMessage />`, but you can see how only using `<FormattedMessage />` could lead to deeper nesting as well.

```jsx
<FormattedMessage id="input-label">
  { (label) =>
        <FormattedMessage id="input-placeholder>
            { (placeholder) =>
                <Input label={label} placeholder={placeholder} />
            }
        </FormattedMessage>
  }
</FormattedMessage>
```

In this case, using `injectIntl` offers a terser bit of code:

```jsx
import { injectIntl } from 'react-intl'

const I18nLabel = ({ labelId, placeholderIntl, intl }) => (
  <Input
    label={intl.formatMessage({ id: labelId })}
    placeholder={intl.formatMessage({ id: placeholderId })}
   />
)

export default injectIntl(I18nLabel)
```

The original maintainer of react-intl has [noted that](https://github.com/yahoo/react-intl/issues/749#issuecomment-265600521):

> Using `context` directly works today, but not recommend because it could change in the future. The officially supported way is to wrap your component with the injectIntl() HoC. 

So I think we should be moving away from contextTypes.

**Comment by tbiethman** [comment]
React does recommend using their new `contextType` specification for simple components that use a single Context consumer. I don't think we should recommend not using it

**Comment by noahbenham** [comment]
That's great perspective, thank you @tbiethman. Out of curiosity, what other context types would you expect in the future?

**Comment by bjankord** [comment]
In my mind, I'm leaning towards recommending `<FormattedMessage />` first, if you need a string, use the render prop version, if get into a situation where you are [nesting multiple render prop based `<FormattedMessage />` components](https://github.com/cerner/terra-ui/issues/119#issuecomment-437230021), use `injectIntl`.

I'm curious to hear what @tbiethman, @JakeLaCombe, @nickpith, @dev-cprice, @noahbenham, and @RHolland13 think about this approach. 

The other part of this issue would be documenting how to test these different approaches with Jest/Enzyme. 

I know @nickpith recently worked on a contribution to https://github.com/joetidee/enzyme-react-intl that makes loading translations optional. 

> Rather than using a real translation file or a mock object where I have to define all the possible keys. It would be easier to use if the default behavior of the *WithIntl methods just used the translation key as the value rendered in a component during testing.

I'd like to dig into this approach some more as I think it will reduce the testing complexity, shoudn't need to call aggregate-translations in jest setup anymore with this I believe.

**Comment by noahbenham** [comment]
In theory, I like the idea of making loading translations optional as it reduces complexity. However, I'm also concerned it would reduce test quality. I've made it a point to explicitly test string translations in our component tests to ensure the requested key exists in the real translation file and is still the expected value. Correlating these leads to stronger tests in my opinion.

**Comment by tbiethman** [comment]
@bjankord That recommendation makes sense to me. 

@noahbenham While Context usage has fewer use cases for atomic components (intl being the main one right now), I see Context being heavily used in application architectures for broad communication needs. For example, there's a PR out now for the terra-disclosure-manager that converts it to a context-based API: https://github.com/cerner/terra-framework/pull/318. 

Previously, the DisclosureManager utilized prop injection to provide its APIs. The issue with prop injection at scale is that it is obtrusive to components that neither need the functionality nor expect that prop to be jammed into their component. Consumers end up asking themselves "Where is this prop coming from?" and "Why do I have to pass this value to my child components that need it? How do I know what components need it?". These questions don't have helpful answers.

Moving to Context requires components that consume those APIs to opt-in to using them and allows components that don't to ignore it altogether. This is much less obtrusive to consumers while providing  the same functionality, and I think it allows Terra to provide some semblance of framework-level components without being too restrictive to consumers.

Regarding your comment above regarding using translated string values, could you validate those same strings using wdio visual regression vs. within your jest snapshots? It'd be ideal to test in both places, but given the increased complexity, limiting your testing concerns within Jest (if possible) seems appropriate.

**Comment by noahbenham** [comment]
I haven't seen the implementation of context in DisclosureManager (out of the office until Tues) but I very much like that approach. The current API contract feels cumbersome.

We could test this with wdio but I question whether the overhead introduced by testing every iteration of a component's possible string displays with wdio is an improvement over the current complexity of calling aggregateTranslations in jestSetup.

Are there other hidden complexities we're trying to solve for by eliminating translation loading in Jest tests?

**Comment by noahbenham** [comment]
My concern with mocking around formatMessage is it doesn't correlate the ID in your component to the value in the actual JSON. You could easily change the key/values in ‘en.json‘ and your tests would happily pass.

I can definitely see how snapshot testing is hindered by real translations. However, is that only a problem when using injectIntl? We've been happily writing Jest snapshot tests for our components that use ‘contextTypes‘ without issue.

It seems optionally loading translations in tests could be preferable when testing components using ‘injectIntl‘ but I wonder if this should be universally applicable for consumers using ‘contextTypes‘, if that's a strategy we want to support.

**Comment by emilyrohrbough** [comment]
+1 to @bjankord recommended approach to using `<FormatMessage />` when it is possible to render a component and then using `injectIntl()` when a string prop is required. This aligns with [react-intl’s definition of injectIntl’s usage](https://github.com/yahoo/react-intl/wiki/API#injection-api)


> React Intl provides an API to inject the imperative formatting API into a React component via its props. This should be used when your React component needs to format data to a string value where a React element is not suitable; e.g., a title or aria attribute, or for side-effect in componentDidMount.

**Comment by nickpith** [comment]
+1 to all @bjankord's suggestions. 

In my opinion, the usage of old contextTypes or new contextType to get the `intl` object should be stopped because it is exposing the actual implementation details of `react-intl`. All usage should be based on `react-intl` guidelines and if you need access to the `intl` object, you should use `injectIntl()` as they intend. I don't believe them make any guarantees from an API perspective that `intl` is in the context.

**Comment by bjankord** [comment]
Noting some different ways to test with react-intl:

* https://github.com/joetidee/enzyme-react-intl
* https://blog.theodo.fr/2017/12/clean-tests-react-intl-missing-message-errors-console/

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-ui/pull/132
