### ISSUE TITLE
Preparing for next OCS theme related major version bump

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#121]
### [terra-core PR](https://github.com/cerner/terra-core/pull/2133)
Terra Core update has been released.

**Comment by emilyrohrbough** [comment]
Lets make major dependencies a peer dependency. This should clear up some confusion on some major provided dependencies of Terra's consumption we have tried to manage. As long as `^` is used to allow any minor version, consumer would still pull in the same version.

For example, lets move `webpack` to be a peer of `terra-toolkit` and lets move `terra-toolkit` to be a peer of `terra-dev-site`. This would be like making react a peer of all terra components.

**Comment by bjankord** [comment]
We've cut the release on the terra-core components. terra-framework and terra-clinical updates coming soon.

**Comment by bjankord** [comment]
Cut the release on terra-framework and terra-clinical components.
