### ISSUE TITLE
Icons - Do not export from a central file

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#127]
This will import all of our icons. I was hoping this would only import the file we require, but this is not the case.
```
import { IconSuccess } from 'terra-icon';
```

This will only import the IconSuccess code.
```
import IconSuccess from 'terra-icon/lib/icon/IconSuccess';
```

To complete this issue, remove this file: https://github.com/cerner/terra-ui/blob/master/packages/terra-icon/src/Icon.jsx

**Comment by bjankord** [comment]
Fixed in #128
