### ISSUE TITLE
terra-toolkit: Unable to resolve path to module 'html-webpack-plugin'

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#136]
Terra-toolkit requires the HtmlWebpackPlugin, but it is not included in its dependencies:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
```
https://github.com/cerner/terra-ui/blob/master/packages/terra-toolkit/tests/test.config.js#L10

https://github.com/cerner/terra-ui/blob/master/packages/terra-toolkit/package.json#L32-L45

**Comment by bjankord** [comment]
Fixed in #134
