### ISSUE TITLE
Audit doc site for accessibility issues

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#138]
# Issue Description
To help ensure our documentation is accessible, we should audit it for Section 508 and WCAG 2 AA issues that can be determined programmatically. 

Recommend using https://www.npmjs.com/package/axe-puppeteer for automation.

**Comment by ryanthemanuel** [comment]
@bjankord do we want to have some criteria of when this is done?

**Comment by bjankord** [comment]
Yeah, I think the PR Alex out will be enough to consider this issue as done. We can run the scripts he's adding periodically on the doc site to see if any issues come up.

**Comment by emilyrohrbough** [comment]
One idea would be to run an audit for each terra-ui PR via danger and then we can post a danger message to the PR with the results

**Comment by bjankord** [comment]
Issues on the following pages were detected:

* https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/about
* https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/example
* https://engineering.cerner.com/terra-ui/#/components/terra-application-name/application-name/application-name
* https://engineering.cerner.com/terra-ui/#/components/terra-application-utility/application-utility/application-utility
* https://engineering.cerner.com/terra-ui/#/components/terra-avatar/avatar/avatar
* https://engineering.cerner.com/terra-ui/#/components/terra-brand-footer/brand-footer/brand-footer
* https://engineering.cerner.com/terra-ui/#/components/terra-clinical-data-grid/clinical-data-grid/clinical-data-grid
* https://engineering.cerner.com/terra-ui/#/components/terra-clinical-item-collection/clinical-item-collection/clinical-item-collection
* https://engineering.cerner.com/terra-ui/#/components/terra-clinical-onset-picker/clinical-onset-picker/clinical-onset-picker
* https://engineering.cerner.com/terra-ui/#/components/terra-dialog-modal/dialog-modal/dialog-modal
* https://engineering.cerner.com/terra-ui/#/components/terra-disclosure-manager/disclosure-manager/upgrade-guide
* https://engineering.cerner.com/terra-ui/#/components/terra-popup/popup/popup
* https://engineering.cerner.com/terra-ui/#/components/terra-slide-panel-manager/slide-panel-manager/slide-panel-manager
