### ISSUE TITLE
Terra i18n Testing Guidance

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-ui#143]
# Issue Description

Looking at the [Testing Components Which Include Translations guide](https://github.com/cerner/terra-ui/blob/master/src/terra-dev-site/guide/Internationalization/TestingComponentsWhichIncludeTranslations.f.guide.md#testing-components-which-include-translations), it says to use `enzyme-react-intl` (which needs a new release so that each method is decoupled from actual translations, see: [enzyme-intl](https://github.com/dev-cprice/enzyme-intl) will be moving this to toolkit soon 😉) as well as putting the following snippet in the jest setup config file:

```js
import aggregateTranslations from 'terra-toolkit/scripts/aggregate-translations/aggregate-translations';

aggregateTranslations();
```

Why should a test be concerned with ***actual translations***? Putting that code snippet in the setup file can ***`D R A S T I C A L L Y`*** slow down jest tests, which should be fast (unlike a certain functional/visual regression test suite ***coughwdiocough*** 😒😒😒).

![gottagofast](https://media.giphy.com/media/6bt7096m6fy1i/giphy.gif)

I propose that we follow the [react-intl docs](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#jest-mock) suggestion and mock out translations. We can decouple tests from translations which is good because:
* faster tests
* less brittle tests 
* mocking out formatMessage, [like so](https://github.com/dev-cprice/enzyme-intl/blob/master/src/index.js#L15) will have expected translation ids in the snapshots/tests

If we want to make sure that all translations are present, we should make a tool that:
* gets all the keys from each `translations/*.json` file and ensure that each file has every key, e.g.:

```js
const fs = require('fs-extra');

const translationsDir = './translations';
const translationFilePath = file => `${translationsDir}/${file}`;

const extractLocale = (file = '') => {
  const indexOfExt = file.indexOf('.json');
  return indexOfExt > 0 ? file.slice(0, indexOfExt) : '';
};

const allTranslations = () => {
  try {
    const translationFiles = fs.readdirSync(translationsDir);

    const translations = translationFiles.reduce((acc, file) => ({
      ...acc,
      [extractLocale(file)]: fs.readJsonSync(translationFilePath(file)),
    }), {});

    return translations;
  } catch (e) {
    console.error(e);
  }

  return {};
};

const translationsObj = allTranslations();
const standard = translationsObj.en;

const ensureAllKeysExist = (compareWith = {}) => (translationsDictionary = {}) => {
  const differences = Object.entries(translationsDictionary).reduce((acc, [locale, translations]) => {
    const diff = { ...compareWith, ...translations };

    return {
      ...acc,
      [locale]: Object.entries(diff).filter(([k, _]) => !(k in compareWith)).reduce((a, [k, v]) => ({ ...a, [k]: v }), {}),
    };
  }, {});

  Object.entries(differences).forEach(([locale, translations]) => {
    if (Object.entries(translations).length > 0) {
      console.error(`locale ${locale} has the following differences: ${JSON.stringify(translations, undefined, 2)}`);
    }
  });
};

ensureAllKeysExist(standard)(translationsObj);
```
* Makes sure that every call to `intl.formatMessage({ id: '...' })` and `<FormattedMessage id="..." />` has a corresponding entry for each id in each locale

## Additional Info

`react-intl` has been compiled weird, so it's kind of hard to make a reusable component that can be imported, but we should suggest putting the following under `app-name/__mocks__/react-intl.js`:

```js
/**
 * See: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#jest-mock
 */
const { createElement } = require('react');
const Intl = require.requireActual('react-intl');

const mockIntl = {
  defaultLocale: 'en',
  formatDate: (date, options) => `${date}`,
  formatHTMLMessage: ({ id }, options) => id,
  formatMessage: ({ id }, options) => id,
  formatNumber: (value, options) => `${value}`,
  formatPlural: (value, options) => `${value}`,
  formatTime: (value, options) => `${value}`,
  formatRelative: (value, options) => `${value}`,
  now: () => 0,
};

Intl.injectIntl = (Node) => {
  const renderWrapped = props => createElement(Node, Object.assign({}, props, { intl: mockIntl }));
  renderWrapped.displayName = Node.displayName || Node.name || 'Component';
  return renderWrapped;
};

module.exports = Intl;
```

Then in their `jestSetup.js`:

```js
...

jest.mock('react-intl');
```

It has also been suggested to add a `"pretest"` script which just runs `aggregateTranslations` once per test run, not before every test.

![image](https://user-images.githubusercontent.com/34115417/51756880-a1477780-2087-11e9-9ebf-8b4a3dca7a38.png)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Fast.

## Current Behavior

Slow.

**Comment by dev-cprice** [comment]
It is also possible to simply instruct consumers to call `aggregateTranslations()` in their test script file (if present), else in a `pretest` script. cc: @nickpith @bjankord

**Comment by dev-cprice** [comment]
The only issue I have with https://github.com/joetidee/enzyme-react-intl is that it [hasn't been released in months](https://www.npmjs.com/package/enzyme-react-intl?activeTab=versions)

![image](https://user-images.githubusercontent.com/34115417/51917663-a0735600-23a5-11e9-820e-dce1e17ecae4.png)

I've talked with @bjankord and @nickpith about moving https://github.com/dev-cprice/enzyme-intl into terra-toolkit since it actually contains the decoupling of translations. 

---

In my example above, I was simply demonstrating what could be done, but it'd be nice if the source of truth came from the code itself: scan the code for all uses of `intl.formatMessage({ id: ... })` and `<FormattedMessage id="..." />`, reduce down to a list of keys and then match on that. 

(I don't necessarily agree with this, but..) I've heard people argue in the past that tests should be able to find the keys that are missing for any locale. The problem for this is that it requires you to run the tests in all locales you support. Which a lot of apps only support a small subset of [terra-toolkit supported i18n locales](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/i18nSupportedLocales.js)

The problem with relying on Jest to throw errors is that they don't fail tests. But if a test were to "fail" for this reason, then it would imply to me that it checked all available locales and would say _"hey, this **locale** is missing the key 'foo'"_

And I definitely agree that this should only be concerned with the app's specific translations being used.

---

As for when to run the aggregateTranslations script, it works incredibly well if you run it before Jest is run in the test script, e.g.: [create react app test script](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/test.js#L135-L138)

```jsx
const aggregateTranslations = require('terra-toolkit/scripts/aggregate-translations/aggregate-translations');

// Prevent intlLoaders error 🙅‍♂️ 
// https://github.com/cerner/terra-core/issues/1964
aggregateTranslations();

// run Jest ✌️ 
jest.run(argv);
```

**Comment by bjankord** [comment]
I like the idea of recommending running aggregate translations in Jests gobalSetup. I'd like to test that idea out some more.

**Comment by bjankord** [comment]
Looked into adding a Jest globalsetup file.
Created a `jestglobalsetup.js` file. This file is not parsed by babel so need to use ES5 syntax. Added the following to the file:
```
const aggregateTranslations = require('terra-toolkit/scripts/aggregate-translations/aggregate-translations');

module.exports = () => {
  aggregateTranslations();
};
```
Then I added `globalSetup: './jestglobalsetup.js',` to the jestconfig.js file.

**Jest test time stats *with global setup* for aggregating translations:**
```
Tests:       932 passed, 932 total
Snapshots:   546 passed, 546 total
Time:        9.251s
```

**Jest test time stats *without global setup* for aggregating translations:**
```
Tests:       932 passed, 932 total
Snapshots:   546 passed, 546 total
Time:        9.2s
```
