### ISSUE TITLE
Update how we handle dependencies used for examples and test files in terra components.

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#165]
## Current Behavior
Currently, we mark terra packages that we pull into other terra packages that are used solely for test or examples as dependencies. The idea behind this is that we include our test files in our distributed package and this allows us or anyone else to reuse those test files when creating a theme to help validate the theme.

## Concerns with this approach
By marking packages that we pull in solely for examples or test files but are not actually part of the source code for the component as dependencies, we require more major version bumps across components as we make non-passive changes to components.

For example, terra-date-picker has an dependency on terra-modal-manager. The modal-manager is not needed for any of the source code for terra-date-picker. We pull in terra-modal-manager for examples and test files to show and test how a date-picker works when rendered inside of the modal-manager. 

If we were to major version bump terra-modal-manager, we would need to cut a major version bump on its dependents, like terra-date-picker which pulls in terra-modal-manager as a dependency, to reduce the case that teams pull in multiple versions of terra-modal-manager.

## Proposal
To mitigate the growing major version bumps across packages that this dependency approach creates, I propose we switch to marking these packages that are not part of a components source code but only used for tests or examples as devDependencies.

## What this resolves
Going back to terra-date-picker example, by marking terra-modal-manager as a devDependency, there is less concern with bumping terra-modal-manager major versions as that package will not actually be pulled into a consumers app when they pull in terra-date-picker. A major version bump to terra-modal-manager would not necessitate a major version bump of terra-date-picker.

## Issues this creates
For people that are pulling in our terra components and wanting to use our test files to help with theming, they will no longer have npm install the dependencies needed for the test file examples.

I think there are some ways to mitigate this. One idea we've been talking about is who creates themes. Its seems like we've landed a consensus on only the terra team should be creating themes. If this is something we still agree on, I think we can resolve the lack of devDependencies being installed in our theme repos.

By having the theme repos install all terra components, the case where a devDependency that was used in example is not installed goes away.

**Comment by mjhenkes** [comment]
In the leadership meeting we discussed removing cross terra dependencies for both tests and examples. The documentation and tests housed alongside terra components ideally should be focused on the component itself. For cases where we want to integration test how components interact with each other we can create unreleased packages with tests for the components.

Additionally we should look to creating simple reusable test elements (button etc) that we can use for examples. These could be housed along side the doc template.

**Comment by bjankord** [comment]
Planning to break this work into phases.

## Phase 1
### Update package.json files and to move packages we use solely in doc examples and tests to devDependencies

## Phase 2
### Look to creating simple reusable test elements (button etc) that we can use for examples. These could be housed along side the doc template.

## Phase 3
### Create unreleased packages with tests for the components  where we want to integration test how components interact with each other
