### ISSUE TITLE
New relic JS error: "You can't have a focus-trap without at least one focusable element"

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-ui#166]
# Issue Description

[New relic](https://rpm.newrelic.com/accounts/1721539/browser/142381315/errors/details#?selectedItem=You%20can't%20have%20a%20focus-trap%20without%20at%20least%20one%20focusable%20element&selectedTab=instances) is showing a JS error in terra-ui:

"You can't have a focus-trap without at least one focusable element"

This is thrown from focus-trap and focus-trap-react

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

No JavaScript errors

## Current Behavior

![image](https://user-images.githubusercontent.com/4873279/56379987-9c9de580-61d6-11e9-8e38-7398c2de486a.png)

**Comment by yuderekyu** [comment]
Is it possible to increase the date range new relic uses to save logs? I can't find references to this error
