### ISSUE TITLE
Setup i18n and switching locales

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#17]
### Description of Issue
We want to be able to demonstrate how to use our components with different locales. We need to setup our documentation site to allow switching locales. After the locale has been updated, it should persist to the next page.

https://github.com/shakacode/react_on_rails/blob/master/docs/basics/i18n.md
https://github.com/cerner/terra-core/wiki/terra-i18n-Guide
https://github.com/cerner/terra-core/wiki/Terra-i18n-plugin-Guide

**Comment by emilyrohrbough** [comment]
Resolved in #60
