### ISSUE TITLE
basic usage example format rendering improperly

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-ui#215]
# Issue Description

The basic usage example code on [terra-ui](https://engineering.cerner.com/terra-ui/getting-started/terra-ui/basic-usage) is rendering with improper formatting.

![image](https://user-images.githubusercontent.com/34115417/62746002-34883f00-ba13-11e9-8ab1-617519cc440b.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

It should render how it does on [github](https://github.com/cerner/terra-ui/blob/master/src/terra-dev-site/guide/BasicUsage.d.guide.md)

![image](https://user-images.githubusercontent.com/34115417/62746010-436ef180-ba13-11e9-9c6e-0c1d2a218de9.png)

**Comment by bjankord** [comment]
Looks like this line is causing the formatting to be off: https://github.com/cerner/terra-ui/blob/master/dev-site-config/IllustrationGrid.scss#L9

I'll take a look, I remember adding this style to fix some wrapping but missed that it removed the space formatting as well.
