### ISSUE TITLE
New Relic Error "Cannot read property 'scrollHeight' of null"

### ISSUE THREAD

**Issue by ShettyAkarsh** [cerner/terra-ui#221]
# Issue Description
Error"'Cannot read property 'scrollHeight' of null" is being logged in New Relic https://rpm.newrelic.com/accounts/1721539/browser/142381315/errors/details#?tw_start=&tw_end=now&tw_offset=604800000&selectedItem=Cannot%20read%20property%20'scrollHeight'%20of%20null&selectedTab=instances 

for the following below URL's.

/terra-ui/components
/terra-ui/components/terra-text/text/text
/terra-ui/components/terra-alert/alert/alert
/terra-ui/components/terra-button/button/button
/terra-ui/components/terra-search-field/search-field/search-field
/terra-ui/components/terra-form-field/form-field/form-field
/terra-ui/components/terra-image/image/image
/terra-ui/components/terra-brand-footer/brand-footer/brand-footer

**Comment by ryanthemanuel** [comment]
This was likely fixed here: https://github.com/cerner/terra-framework/commit/4a41737325ea81656c60520c26d37d6f512556f0 But was just released today.  Once we redeploy terra-ui this will go away.
