### ISSUE TITLE
Update package README files to point to new repo

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#23]
### Description of Issue
The README inside of `packages/terra-component/docs/` and the README in `packages/terra-component/`, there are references to the old repos. 

These files include the following lines:

```
- [Download the latest version](https://github.com/cerner/terra-arrange/archive/master.zip)
- Clone the repo: `git clone https://github.com/cerner/terra-arrange.git`
```

These need to be updated to the following:

```
- [Download the latest version](https://github.com/cerner/terra-ui/archive/master.zip)
- Clone the repo: `git clone https://github.com/cerner/terra-ui.git`
```

- [x] terra-arrange
- [x] terra-button
- [x] terra-grid

TODO:
Add other repos we need to do this for to checklist.

**Comment by bjankord** [comment]
Do we still want people to clone the repo to use packages or should we direct people to use releases on npm? @Matt-Butler @mjhenkes

**Comment by Matt-Butler** [comment]
I'm fine if we want to leave 
```
- Clone the repo: `git clone https://github.com/cerner/terra-ui.git`
```
in the root readme. I don't think it belongs in every package.

**Comment by bjankord** [comment]
This has now been resolved.
