### ISSUE TITLE
React-router hash links

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#29]
# Issue Description
We want to be able to use hash-links with react router. This issue explains more about it: https://github.com/ReactTraining/react-router/issues/394

We are using react-router 3.0.5.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by Matt-Butler** [comment]
I tried using the hashLinkScroll provided here:
https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604
This fix did not work.

Hash links work for the react_on_rails tutorial site, but they are doing server-side rendering. 
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/config/initializers/react_on_rails.rb#L34

**Comment by bjankord** [comment]
Hash links are working with the latest terra-dev-site. See getting started page for example.
