### ISSUE TITLE
Remove all obsolete snapshots

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#3]
```
Snapshot Summary
 › 36 obsolete snapshots found, run with `npm test -- -u` to remove them.
```
To remove obsolete snapshots, the script above must be executed in each package. It would be convenient to have the option of removing all obsolete snapshots in the repository.

**Comment by bjankord** [comment]
#7 Removes the 36 obsolete snapshots. I'll work on adding a script to clean snapshots globally.

**Comment by bjankord** [comment]
#12 Adds scripts to run this across the packages we have now. We'll need to add scripts like this to the components we import.
