### ISSUE TITLE
Update packages eslintignore to point to configuration in root

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#30]
When running `npm run lint` in an individual package, the .eslitignore file is not honored. 

Update
```
    "lint:js": "../../node_modules/.bin/eslint **/*.js, **/*.jsx",
```
to
```
    "lint:js": "../../node_modules/.bin/eslint **/*.js, **/*.jsx --ignore-path ../../.eslintignore",
```

**Comment by Matt-Butler** [comment]
http://eslint.org/docs/user-guide/configuring#using-an-alternate-file

**Comment by bjankord** [comment]
@Matt-Butler and I tested this some more.

We landed on updating 
`"lint:js": "../../node_modules/.bin/eslint **/*.js, **/*.jsx",`
to
`$(cd ..; npm bin)/eslint --ext .js,.jsx . --ignore-path ../../.eslintignore`

For the component package.json files
