### ISSUE TITLE
Update jestconfig.json

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#32]
I don't think this file is currently being used: https://github.com/cerner/terra-ui/blob/master/jestconfig.json. 

Can we remove it?

**Comment by bjankord** [comment]
This is used here:
* https://github.com/cerner/terra-ui/blob/master/packages/terra-button/package.json#L35
* https://github.com/cerner/terra-ui/blob/master/packages/terra-arrange/package.json#L35

**Comment by Matt-Butler** [comment]
In the root directory, I don't think these paths can be correct:
https://github.com/cerner/terra-ui/blob/master/jestconfig.json#L3
https://github.com/cerner/terra-ui/blob/master/jestconfig.json#L6

**Comment by Matt-Butler** [comment]
Nm, I don't think this is an issue. The path is relative to the package, not this file.
