### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#36]
# Issue Description

Add favicon to terra-ui.com

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by Matt-Butler** [comment]
https://css-tricks.com/give-development-domain-different-favicon-production/
^ I like this idea where they use a different favicon for development than prod.

**Comment by emilyrohrbough** [comment]
https://github.com/cerner/terra-dev-site/issues/58
