### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#43]
# Issue Description

The terra-ui.com bundle is very large. We want to seperate the site into several bundles. 
We can use [dynamic imports](webpack) with webpack to make this easier. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
Google Lighthouse Audit results from 10/27/2018

<img width="1440" alt="screen shot 2018-10-27 at 6 54 53 am" src="https://user-images.githubusercontent.com/633148/47603690-54cf9b80-d9b5-11e8-9475-bd500c509cd4.png">
