### ISSUE TITLE
Upgrade version of React?

### ISSUE THREAD

**Issue by dwwinters** [cerner/terra-ui#469]
# Feature Request

## Description
Are there plans to upgrade from React v16?  I realize there are breaking changes going from v16 to v17 to v18, but was wondering if this was on the development roadmap.

## Additional Context / Screenshots
n/a

## @ Mentions
n/a

**Comment by benbcai** [comment]
Thanks for contacting us. We have an internal issue created for tracking the React v17/v18 upgrade. We have not yet prioritize this work on our roadmap so we currently do not have a timeline when this is expected to be completed. 

Thank you for using terra-ui!

**Comment by benbcai** [comment]
I am closing this issue in favor of the internal issue (UXPLATFORM-6517) that has been logged for tracking this work.
