### ISSUE TITLE
Create "Thing" to Listen for Terra Master Branch Updates

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-ui#59]
# Issue Description
Terra-UI needs to display the most up-to-date terra-components available to consumer. With the completion of #57, this will be possible, however every time the master branch of a terra-repo is updated, this site will need manually redeployed. This should be automated

### Expected Behavior
Lets add some sort of bot or webhook that will listen/receive master-branch merge updates. Upon receiving the update this will trigger a new deployment build to keep terra-ui in sync.

**Comment by tbiethman** [comment]
![https://vignette.wikia.nocookie.net/marveldatabase/images/2/23/Benjamin_Grimm_%28Earth-616%29_from_Heroic_Age_Advertisement.jpg/revision/latest?cb=20110622061953](https://vignette.wikia.nocookie.net/marveldatabase/images/2/23/Benjamin_Grimm_%28Earth-616%29_from_Heroic_Age_Advertisement.jpg/revision/latest?cb=20110622061953)

**Comment by bjankord** [comment]
This may be possible with [GitHub actions](https://github.com/features/actions/) ?

**Comment by emilyrohrbough** [comment]
@cerner/terra I feel like this is no longer needed since terra-ui only presents documentation on the latest releases at this point.

**Comment by bjankord** [comment]
This is something I'm still interested in. I think it would be worthwhile to look into [renovate](https://github.com/renovatebot/renovate)

The idea with using renovate is that we could receive automated pull requests whenever dependencies need updating based on when we cut terra releases. I believe we could also have renovate do auto PR merging for minor and patch releases if TravisCI passes.

**Comment by mjhenkes** [comment]
we've got a cron job, it's a good enough thing
