### ISSUE TITLE
Rename Repo from terra-ui.com to terra-ui

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-ui#65]
# Issue Description
I propose we rename this repo from terra-ui.com to terra-ui. The reason for this change is to make the gh-pages url less strange. Currently the url is engineering.cerner.com/terra-ui.com which is weird. After the name change it would be engineering.cerner.com/terra-ui

**Comment by emilyrohrbough** [comment]
+1

**Comment by mjhenkes** [comment]
@emilyrohrbough the current plan would be to redirect from terra-ui.com to engineering.cerner.com/terra-ui

**Comment by mjhenkes** [comment]
@ryanthemanuel, @JakeLaCombe Could i get a 👍 from you guys on this change?

**Comment by ryanthemanuel** [comment]
👍
