### ISSUE TITLE
yarn install => yarn add

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#84]
We have several packages that have documentation that states `yarn install terra-*`. The correct syntax is `yarn add terra-*`.

https://github.com/cerner/terra-ui/blob/master/packages/terra-button/docs/README.md#getting-started

**Comment by bjankord** [comment]
So for this work we just need to check every `terra-ui/packages/terra-component/docs/README.md` file in all the packages and make sure it uses the `yard add` syntax rather than `yarn install`
