### ISSUE TITLE
Replace UI's Footer with terra-brand-footer

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-ui#94]
# Issue Description
On the home page we use a custom footer. We should update this to use terra-brand-footer.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Use our pretty react components 

## Current Behavior
Being custom

**Comment by Blackop778** [comment]
Going to hopefully get cerner/terra-framework#202 published first

**Comment by Blackop778** [comment]
<img width="1440" alt="screen shot 2018-06-13 at 5 09 21 pm" src="https://user-images.githubusercontent.com/11130785/41381257-c0817608-6f2c-11e8-94b4-f6c6ee24b00f.png">
Here is the current design including changes from cerner/terra-framework#202. Feedback is welcome.
